### ISSUE TITLE
AddTextAsync_Can_Be_Retrieved_With_ReadTextAsync Failing on windows

### ISSUE THREAD

**Issue by atlassanjay** [catalyst-network/Catalyst.Framework#986]
Failing test: AddTextAsync_Can_Be_Retrieved_With_ReadTextAsync

Error Message:
```
System.IO.IOException : The process cannot access the file 'd:\a\1\s\src\Catalyst.Core.Modules.Dfs.Tests\bin\Debug\netcoreapp2.2\AddTextAsync_Can_Be_Retrieved_With_ReadTextAsync_1909160950301306\dfs\udsaeiehkvx6qgerv7j4dycuhme2zw2aajif767oe3xf7yqihertuvhevq' because it is being used by another process.
```

Stack Trace:
```
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at Catalyst.Core.Modules.Dfs.DevDfs.ReadTextAsync(String id, CancellationToken cancellationToken) in d:\a\1\s\src\Catalyst.Core.Modules.Dfs\DevDfs.cs:line 96
   at Catalyst.Core.Modules.Dfs.Tests.IntegrationTests.DevDfsTests.AddTextAsync_Can_Be_Retrieved_With_ReadTextAsync() in d:\a\1\s\src\Catalyst.Core.Modules.Dfs.Tests\IntegrationTests\DevDfsTests.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by monsieurleberre** [comment]
looks OK now :)
